### PR TITLE
James/geometry

### PR DESCRIPTION
**Pull request by jameshod5**
There has been many additions for the geometry PR, mainly for the creation and organisation of the geometry files that we use to ingest that data.

Nothing has changed with process of the ingestion workflow, only that we now need to use Git LFS to pull the data files that are used. The instructions to install Git LFS are not on the README at the moment.

Everything to do with geometry now exists in `geometry` directory, including the notebooks for creating the data, the raw data that has been transformed and the geometry data in its final form (`geometry/data`). Obviously all of these do not have to exist in the repo for it to work, just the geometry parquet files, but I have left them in case it is needed again.

OMAHA geometry does exist in Git LFS, but has not been added to the ingestion due to varying shot ranges they exist for. Leaving as a draft PR due to this.

I have ingested a shot with all the sources that have geometry added to them that you can look at on CSD3 under : `/home/ir-hods1/projects/fair-mast-ingestion/data/local/30420.zarr`. You can either ingest yourself or look at this one to see how the new geometry is laid out.

Can reviewers:
- look at the code and see if it is sensible 
- look at the structure of the geometry data in the ingested shot

### CODE REVIEW

**Review by samueljackson92 — CHANGES_REQUESTED** [review]
Generally looks good, but see comment about tensorization.

**Comment by samueljackson92** [comment]
@jameshod5 Ok, so I see what you mean now.

So I don't think we should have two indicies like this:

image

I think they should 1) be called the same thing, and 2) only the geometry values for the channels we observe should be in the shot?

What do you think @NathanCummings?

**Comment by jameshod5** [comment]
I have fixed the channels, but some of the sources (such as the raw ones, XMA) only have a time dimension on CCBV for example. Not sure how to go about fixing that at the moment, not sure if its a UDA thing

**Comment by samueljackson92** [comment]
It they should be concatenated along a new axis right? So it becomes `(channel, time)`

**Comment by jameshod5** [comment]
I thought it'd do that but no, gonna have a look this afternoon

**Comment by jameshod5** [comment]
Hopefully that's sorted now

**Comment by samueljackson92** [comment]
This is looking good, but can you please fix the merge conflict?

**Comment by jameshod5** [comment]
Are you happy for it to merge without the OMAHA data in place?

**Comment by samueljackson92** [comment]
Yes, but create a follow up issue and link it here.


________________________________

**Comment by jameshod5** [comment]
#32 is an extension of this PR, adding OMAHA geometry

**Review by samueljackson92 — APPROVED** [review]

**Pull request merged**
